# Generated by Django 2.1.2 on 2018-11-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auto_20181124_2122'),
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='nlp_content',
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('MONEY', 'Monetary values with unit.')], default='MONEY', max_length=12),
        ),
        migrations.DeleteModel(
            name='NLPContent',
        ),
    ]
