# Generated by Django 2.1.2 on 2018-11-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
        ('cases', '0013_auto_20181105_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='nlp_content',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nlp.NLPContent'),
        ),
    ]
