# Generated by Django 2.1.2 on 2018-11-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
        ('cases', '0014_case_nlp_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='nlp_content',
        ),
        migrations.AddField(
            model_name='case',
            name='nlp_entities',
            field=models.ManyToManyField(blank=True, to='nlp.Entity'),
        ),
    ]
