# Generated by Django 2.1.2 on 2019-03-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_add_db_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='nlp_entities',
        ),
    ]
