# Generated by Django 5.1.15 on 2026-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_apitoken_rate_limit"),
        ("cases", "0026_convert_utf8mb4"),
        ("courts", "0019_court_created_by_token_court_created_date_and_more"),
        ("sources", "0002_alter_source_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["review_status", "court", "-date"],
                name="cases_status_court_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["review_status", "-updated_date"],
                name="cases_status_updated_idx",
            ),
        ),
    ]
