# Generated by Django 5.1.15 on 2026-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0027_add_review_status_query_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="references_extracted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent run of the references extract_refs processing step. Null when the step has never run for this case — distinguishes 'extraction found no refs' from 'extraction never ran' in the API/MCP.",
                null=True,
            ),
        ),
    ]
