# Generated by Django 5.1.15 on 2026-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0028_case_references_extracted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="citing_cases_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Denormalized number of distinct accepted cases that cite this case (how often this decision is referenced). Recomputed off the hot path by the ``update_citing_counts`` management command and mirrored into Elasticsearch (``CaseIndex.citing_cases_count``) to power most-cited / landmark-precedent sorting. Approximate between recompute runs.",
            ),
        ),
    ]
