# Generated by Django 5.2.16 on 2026-09-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_userprofile_lifecycle_fields"),
        ("cases", "0029_case_citing_cases_count"),
        ("courts", "0019_court_created_by_token_court_created_date_and_more"),
        ("sources", "0002_alter_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="court_jurisdiction",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Denormalised copy of court.jurisdiction (do not set directly)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="court_level_of_appeal",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Denormalised copy of court.level_of_appeal (do not set directly)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["review_status", "court_jurisdiction", "date"],
                name="cases_status_jur_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["review_status", "court_level_of_appeal", "date"],
                name="cases_status_loa_date_idx",
            ),
        ),
    ]
