# Generated by Django 5.2.16 on 2026-10-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0031_backfill_court_facets"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="review_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When review_status or review_note last changed (set automatically on save).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="review_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff-only note on the review decision (e.g. why a case was rejected after a privacy report). Never serialized, dumped or shown publicly. A rejected case with a note cannot be re-accepted via the API.",
            ),
        ),
    ]
