# Generated by Django 5.2.16 on 2026-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0031_backfill_court_facets"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="review_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When review_status or review_note last changed (set automatically on save).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="review_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff-only record of the review decision, e.g. a takedown or redaction after a privacy report: report reference, what was removed and why. Never serialized, dumped or shown publicly. A non-empty note blocks re-acceptance via the API; bulk review steps only ever touch pending cases.",
            ),
        ),
    ]
