# Generated by Django 5.2.16 on 2026-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0031_backfill_court_facets"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When a takedown or redaction was applied. Blocks re-acceptance until cleared by staff.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="moderation_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff-only record of the takedown/redaction: report reference, what was removed or redacted, and why. Never exported or shown publicly.",
            ),
        ),
    ]
