# Generated by Django 2.1.2 on 2019-01-15 16:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0017_case_source_file'),
        ('laws', '0018_auto_20181128_1059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='a name for the collection')),
                ('notes', models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='notes about the collection')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Entry is created at this date time')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date time of last change')),
                ('private', models.BooleanField(default=True, help_text='If the collection should be only accessible by the owner')),
                ('user', models.ForeignKey(help_text='The user that owns the collection', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='a name for the favorite')),
                ('notes', models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='notes about the favorite')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Entry is created at this date time')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date time of last change')),
                ('case', models.ForeignKey(blank=True, help_text='The case that is favorited', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case')),
                ('collection', models.ForeignKey(blank=True, help_text='The favorite belongs to this collection', null=True, on_delete=django.db.models.deletion.CASCADE, to='favorites.Collection')),
                ('law', models.ForeignKey(blank=True, help_text='The case that is favorited', null=True, on_delete=django.db.models.deletion.SET_NULL, to='laws.Law')),
                ('user', models.ForeignKey(help_text='The user that owns the favorite', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('case', 'collection', 'user'), ('law', 'collection', 'user')},
        ),
    ]
