# Generated by Django 5.1.15 on 2026-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laws", "0023_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="references_extracted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent run of the references extract_refs processing step. Null when the step has never run for this law section.",
                null=True,
            ),
        ),
    ]
