# Generated by Django 5.2.16 on 2026-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_userprofile_lifecycle_fields"),
        ("laws", "0025_convert_utf8mb4"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="law",
            index=models.Index(
                fields=["review_status", "order"], name="laws_law_status_order_idx"
            ),
        ),
    ]
