# Generated by Django 5.1.15 on 2026-06-27 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_convert_auth_tables_utf8mb4"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional public name; falls back to the username.",
                        max_length=150,
                        verbose_name="Display name",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Company, university, or project (optional).",
                        max_length=200,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("researcher", "Researcher / Academia"),
                            ("journalist", "Journalist"),
                            ("developer", "Developer"),
                            ("legal_tech", "Legal tech / Startup"),
                            ("lawyer", "Lawyer / Legal professional"),
                            ("student", "Student"),
                            ("other", "Other"),
                        ],
                        help_text="How do you use OLDP? (optional)",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "use_case",
                    models.TextField(
                        blank=True,
                        help_text="What are you building with OLDP? (optional)",
                        verbose_name="Use case",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code (optional).",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
                (
                    "newsletter_opt_in",
                    models.BooleanField(
                        default=False,
                        help_text="User requested marketing email. Not a valid consent until confirmed.",
                        verbose_name="Newsletter opt-in",
                    ),
                ),
                (
                    "newsletter_opt_in_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the opt-in checkbox/toggle was set.",
                        null=True,
                        verbose_name="Opt-in requested at",
                    ),
                ),
                (
                    "newsletter_doi_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the confirmation link was clicked. Required to send marketing mail.",
                        null=True,
                        verbose_name="Double-opt-in confirmed at",
                    ),
                ),
                (
                    "consent_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("signup", "Signup form"),
                            ("prompt", "On-login prompt"),
                            ("dashboard", "Dashboard"),
                            ("import", "Imported"),
                        ],
                        help_text="Where the opt-in was captured (audit).",
                        max_length=20,
                        verbose_name="Consent source",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
