# Generated by Django 5.1.15 on 2026-06-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_backfill_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enriched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the profile was first completed and the rate-limit bonus granted.",
                null=True,
                verbose_name="Enriched at",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enrichment_prompted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user was shown the one-time profile-enrichment prompt (set whether they filled it in or skipped, so it is shown once).",
                null=True,
                verbose_name="Enrichment prompted at",
            ),
        ),
    ]
