# Generated by Django 5.1.15 on 2026-06-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_userprofile_enriched_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("researcher", "Researcher / Academia"),
                    ("journalist", "Journalist"),
                    ("developer", "Developer"),
                    ("legal_tech", "Legal tech / Startup"),
                    ("lawyer", "Lawyer / Legal professional"),
                    ("student", "Student"),
                    ("other", "Other"),
                ],
                help_text="How do you use Open Legal Data? (optional)",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="use_case",
            field=models.TextField(
                blank=True,
                help_text="What are you building with Open Legal Data? (optional)",
                verbose_name="Use case",
            ),
        ),
    ]
