# Generated by Django 5.1.15 on 2026-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_userprofile_role_alter_userprofile_use_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="max_api_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Per-user limit on application API tokens. Leave blank to use the system default (API_TOKENS_PER_USER_DEFAULT).",
                null=True,
                verbose_name="Max API tokens",
            ),
        ),
    ]
