# Generated by Django 5.2.16 on 2026-10-06 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_userprofile_lifecycle_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="E-mail address"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("opt_in", "Opt-in requested"),
                            ("confirmed", "Double-opt-in confirmed"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("signup", "Signup form"),
                            ("prompt", "On-login prompt"),
                            ("dashboard", "Dashboard"),
                            ("import", "Imported"),
                            ("lifecycle", "Inactivity lifecycle"),
                            ("account_deletion", "Account deletion"),
                        ],
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "consent_text",
                    models.TextField(
                        blank=True,
                        help_text="Exact wording shown to the user (in their language).",
                        verbose_name="Consent text",
                    ),
                ),
                (
                    "consent_text_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Consent text version"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Recorded at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_consent_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter consent log entry",
                "verbose_name_plural": "Newsletter consent log",
                "ordering": ["-created_at"],
            },
        ),
    ]
