# Generated by Django 5.2.16 on 2026-10-10 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_userprofile_lifecycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="newsletter_unsubscribed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user withdrew the consent; the opt-in audit fields are kept.",
                null=True,
                verbose_name="Unsubscribed at",
            ),
        ),
        migrations.CreateModel(
            name="NewsletterConsentText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                ("language", models.CharField(max_length=8, verbose_name="Language")),
                ("text", models.TextField(verbose_name="Consent text")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter consent text",
                "verbose_name_plural": "Newsletter consent texts",
                "ordering": ["-version", "language"],
                "unique_together": {("version", "language")},
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="newsletter_consent_text",
            field=models.ForeignKey(
                blank=True,
                help_text="The exact wording the user agreed to (audit, kept after unsubscribe).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="accounts.newsletterconsenttext",
                verbose_name="Consent text",
            ),
        ),
    ]
