"""ISO 3166-1 alpha-2 country choices with German display names.

Used for the optional ``UserProfile.country`` dropdown. Kept as static data so
we don't pull in a dependency (django-countries / babel) just for one field.
The most common countries for an OLDP-DE audience (DE/AT/CH) are pinned first;
the rest follow alphabetically by German name.
"""

# (code, German name) — alphabetical by German name.
_REST = [
    ("EG", "Ägypten"),
    ("AL", "Albanien"),
    ("DZ", "Algerien"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AG", "Antigua und Barbuda"),
    ("GQ", "Äquatorialguinea"),
    ("AR", "Argentinien"),
    ("AM", "Armenien"),
    ("AZ", "Aserbaidschan"),
    ("ET", "Äthiopien"),
    ("AU", "Australien"),
    ("BS", "Bahamas"),
    ("BH", "Bahrain"),
    ("BD", "Bangladesch"),
    ("BB", "Barbados"),
    ("BE", "Belgien"),
    ("BZ", "Belize"),
    ("BJ", "Benin"),
    ("BT", "Bhutan"),
    ("BO", "Bolivien"),
    ("BA", "Bosnien und Herzegowina"),
    ("BW", "Botswana"),
    ("BR", "Brasilien"),
    ("BN", "Brunei"),
    ("BG", "Bulgarien"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CR", "Costa Rica"),
    ("DK", "Dänemark"),
    ("DM", "Dominica"),
    ("DO", "Dominikanische Republik"),
    ("DJ", "Dschibuti"),
    ("EC", "Ecuador"),
    ("SV", "El Salvador"),
    ("CI", "Elfenbeinküste"),
    ("ER", "Eritrea"),
    ("EE", "Estland"),
    ("SZ", "Eswatini"),
    ("FJ", "Fidschi"),
    ("FI", "Finnland"),
    ("FR", "Frankreich"),
    ("GA", "Gabun"),
    ("GM", "Gambia"),
    ("GE", "Georgien"),
    ("GH", "Ghana"),
    ("GD", "Grenada"),
    ("GR", "Griechenland"),
    ("GB", "Großbritannien"),
    ("GT", "Guatemala"),
    ("GN", "Guinea"),
    ("GW", "Guinea-Bissau"),
    ("GY", "Guyana"),
    ("HT", "Haiti"),
    ("HN", "Honduras"),
    ("HK", "Hongkong"),
    ("IN", "Indien"),
    ("ID", "Indonesien"),
    ("IQ", "Irak"),
    ("IR", "Iran"),
    ("IE", "Irland"),
    ("IS", "Island"),
    ("IL", "Israel"),
    ("IT", "Italien"),
    ("JM", "Jamaika"),
    ("JP", "Japan"),
    ("YE", "Jemen"),
    ("JO", "Jordanien"),
    ("KH", "Kambodscha"),
    ("CM", "Kamerun"),
    ("CA", "Kanada"),
    ("CV", "Kap Verde"),
    ("KZ", "Kasachstan"),
    ("QA", "Katar"),
    ("KE", "Kenia"),
    ("KG", "Kirgisistan"),
    ("KI", "Kiribati"),
    ("CO", "Kolumbien"),
    ("KM", "Komoren"),
    ("CD", "Kongo (Demokratische Republik)"),
    ("CG", "Kongo (Republik)"),
    ("KP", "Korea (Nord)"),
    ("KR", "Korea (Süd)"),
    ("HR", "Kroatien"),
    ("CU", "Kuba"),
    ("KW", "Kuwait"),
    ("LA", "Laos"),
    ("LS", "Lesotho"),
    ("LV", "Lettland"),
    ("LB", "Libanon"),
    ("LR", "Liberia"),
    ("LY", "Libyen"),
    ("LI", "Liechtenstein"),
    ("LT", "Litauen"),
    ("LU", "Luxemburg"),
    ("MG", "Madagaskar"),
    ("MW", "Malawi"),
    ("MY", "Malaysia"),
    ("MV", "Malediven"),
    ("ML", "Mali"),
    ("MT", "Malta"),
    ("MA", "Marokko"),
    ("MH", "Marshallinseln"),
    ("MR", "Mauretanien"),
    ("MU", "Mauritius"),
    ("MX", "Mexiko"),
    ("FM", "Mikronesien"),
    ("MD", "Moldau"),
    ("MC", "Monaco"),
    ("MN", "Mongolei"),
    ("ME", "Montenegro"),
    ("MZ", "Mosambik"),
    ("MM", "Myanmar"),
    ("NA", "Namibia"),
    ("NR", "Nauru"),
    ("NP", "Nepal"),
    ("NZ", "Neuseeland"),
    ("NI", "Nicaragua"),
    ("NL", "Niederlande"),
    ("NE", "Niger"),
    ("NG", "Nigeria"),
    ("MK", "Nordmazedonien"),
    ("NO", "Norwegen"),
    ("OM", "Oman"),
    ("PK", "Pakistan"),
    ("PW", "Palau"),
    ("PS", "Palästina"),
    ("PA", "Panama"),
    ("PG", "Papua-Neuguinea"),
    ("PY", "Paraguay"),
    ("PE", "Peru"),
    ("PH", "Philippinen"),
    ("PL", "Polen"),
    ("PT", "Portugal"),
    ("RW", "Ruanda"),
    ("RO", "Rumänien"),
    ("RU", "Russland"),
    ("SB", "Salomonen"),
    ("ZM", "Sambia"),
    ("WS", "Samoa"),
    ("SM", "San Marino"),
    ("ST", "São Tomé und Príncipe"),
    ("SA", "Saudi-Arabien"),
    ("SE", "Schweden"),
    ("SN", "Senegal"),
    ("RS", "Serbien"),
    ("SC", "Seychellen"),
    ("SL", "Sierra Leone"),
    ("ZW", "Simbabwe"),
    ("SG", "Singapur"),
    ("SK", "Slowakei"),
    ("SI", "Slowenien"),
    ("SO", "Somalia"),
    ("ES", "Spanien"),
    ("LK", "Sri Lanka"),
    ("KN", "St. Kitts und Nevis"),
    ("LC", "St. Lucia"),
    ("VC", "St. Vincent und die Grenadinen"),
    ("ZA", "Südafrika"),
    ("SD", "Sudan"),
    ("SS", "Südsudan"),
    ("SR", "Suriname"),
    ("SY", "Syrien"),
    ("TJ", "Tadschikistan"),
    ("TW", "Taiwan"),
    ("TZ", "Tansania"),
    ("TH", "Thailand"),
    ("TL", "Timor-Leste"),
    ("TG", "Togo"),
    ("TO", "Tonga"),
    ("TT", "Trinidad und Tobago"),
    ("TD", "Tschad"),
    ("CZ", "Tschechien"),
    ("TN", "Tunesien"),
    ("TR", "Türkei"),
    ("TM", "Turkmenistan"),
    ("TV", "Tuvalu"),
    ("UG", "Uganda"),
    ("UA", "Ukraine"),
    ("HU", "Ungarn"),
    ("UY", "Uruguay"),
    ("US", "USA"),
    ("UZ", "Usbekistan"),
    ("VU", "Vanuatu"),
    ("VA", "Vatikanstadt"),
    ("VE", "Venezuela"),
    ("AE", "Vereinigte Arabische Emirate"),
    ("VN", "Vietnam"),
    ("BY", "Weißrussland"),
    ("CF", "Zentralafrikanische Republik"),
    ("CY", "Zypern"),
]

# Pin the most common OLDP-DE countries first.
_PINNED = [
    ("DE", "Deutschland"),
    ("AT", "Österreich"),
    ("CH", "Schweiz"),
]

COUNTRY_CHOICES = [("", "—")] + _PINNED + sorted(_REST, key=lambda c: c[1])
