"""Generate the law full-name → code search synonyms from the LawBook table.

German laws are cited in case text by their *code* (``KSchG``), but laypeople
search by the full name (``Kündigungsschutzgesetz``). This command renders a
principled, data-derived ``synonym_graph`` ruleset (``name => name, code``)
that the German *search* analyzer loads via ``OLDP_LAW_SYNONYMS_FILE`` so a
full-name query also matches the code. Directional + query-time, so it needs
no reindex and never broadens a code/precise search.

The rules are generated offline (here) rather than at settings time because
the analyzer is configured before the DB is reachable. Regenerate when the
book corpus changes (rare — codes/names are stable), then apply WITHOUT a
reindex via ``scripts/search/apply_search_analyzer.py``.

Usage:
    ./manage.py generate_law_synonyms                 # write to OLDP_LAW_SYNONYMS_FILE
    ./manage.py generate_law_synonyms -o laws.txt     # write to a path
    ./manage.py generate_law_synonyms --to-stdout      # print (review / piping)
"""

import os

from django.core.management import BaseCommand, CommandError

from oldp.apps.laws.law_names import build_law_name_map, law_synonym_rules


class Command(BaseCommand):
    help = "Generate law full-name → code search synonyms from LawBook."

    def add_arguments(self, parser):
        parser.add_argument(
            "-o",
            "--output",
            default=None,
            help="Output file path (default: $OLDP_LAW_SYNONYMS_FILE).",
        )
        # NB: dest must not be "stdout" — that collides with Django's reserved
        # output-stream kwarg on ``call_command``.
        parser.add_argument(
            "--to-stdout",
            dest="to_stdout",
            action="store_true",
            help="Print the rules to stdout instead of writing a file.",
        )

    def handle(self, *args, **options):
        mapping = build_law_name_map()
        rules = law_synonym_rules(mapping)

        header = (
            "# Auto-generated by `manage.py generate_law_synonyms` — do not edit.\n"
            "# Law full-name -> code synonyms (directional, query-time graph).\n"
            f"# {len(rules)} rules.\n"
        )
        body = "\n".join(rules) + ("\n" if rules else "")

        if options["to_stdout"]:
            self.stdout.write(header + body)
            return

        path = options["output"] or os.environ.get("OLDP_LAW_SYNONYMS_FILE", "")
        if not path:
            raise CommandError(
                "No output path: pass --output or set OLDP_LAW_SYNONYMS_FILE "
                "(or use --to-stdout)."
            )
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(header + body)
        self.stdout.write(
            self.style.SUCCESS(f"Wrote {len(rules)} law synonym rules to {path}")
        )
