# Generated by Django 5.1.15 on 2026-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0027_add_review_status_query_indexes"),
        ("laws", "0023_review_status"),
        ("references", "0011_add_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(fields=["law"], name="refs_ref_law_idx"),
        ),
    ]
