# Generated by Django 5.1.15 on 2026-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0028_case_references_extracted_at"),
        ("laws", "0024_law_references_extracted_at"),
        ("references", "0012_add_law_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="law_book_slug",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="reference",
            name="law_section_slug",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["law_book_slug", "law_section_slug"],
                name="refs_ref_law_slugs_idx",
            ),
        ),
    ]
