# Generated by Django 5.1.15 on 2026-06-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0015_convert_references_utf8mb4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereferencemarker",
            name="text",
            field=models.CharField(
                help_text="Text that represents the marker (e.g. § 123 ABC)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="lawreferencemarker",
            name="text",
            field=models.CharField(
                help_text="Text that represents the marker (e.g. § 123 ABC)",
                max_length=1000,
            ),
        ),
    ]
