# Generated by Django 5.1.15 on 2026-06-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0016_alter_casereferencemarker_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="to",
            field=models.CharField(max_length=1000),
        ),
    ]
