# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = "Open Legal Data Platform"
copyright = "2025, Open Legal Data"
author = "Open Legal Data"

# Derive the version from the installed `oldp` package so the docs stay in sync
# with the code. Mirrors the fallback in `oldp/__init__.py`. When the
# sphinx-polyversion driver is active (see below) it overrides this with the
# git ref being built.
try:
    import importlib.metadata

    release = importlib.metadata.version("oldp")
except (importlib.metadata.PackageNotFoundError, ImportError):
    release = "0.10.13"
# The short X.Y version
version = ".".join(release.split(".")[:2])


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "myst_parser",
]

# Register Markdown headings (h1–h3) as cross-reference targets so intra- and
# cross-document `[text](file.md#heading-slug)` links resolve instead of warning.
myst_heading_anchors = 3

# Mock heavy runtime deps so docs build in a lightweight environment
# (Cloudflare Pages, GitHub Actions) without installing the full Django stack.
autodoc_mock_imports = [
    "django",
    "django.db",
    "django.db.models",
    "django.contrib",
    "django.contrib.auth",
    "django.conf",
    "elasticsearch",
    "haystack",
    "rest_framework",
    "configurations",
    "crispy_forms",
    "guardian",
]

# sphinx-polyversion: inject `current` (the GitRef being built) and
# `revisions` (all refs being built) into the Sphinx config namespace.
# Falls back gracefully when polyversion isn't installed (Cloudflare Pages
# single-version build) or the driver isn't active (direct `sphinx-build`).
try:
    from sphinx_polyversion import load
    from sphinx_polyversion.api import LoadError

    # Importing `git` registers `GitRef` with the JSON decoder; without
    # this, `load()` leaves `current` as a raw `__jsonclass__` dict and
    # the `.name` access below raises AttributeError.
    from sphinx_polyversion.git import GitRef  # noqa: F401
except ImportError:
    pass
else:
    try:
        polyversion_data = load(globals())
        if polyversion_data and polyversion_data.get("current"):
            release = version = polyversion_data["current"].name
    except (LoadError, KeyError):
        pass

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates: prepend the polyversion version switcher to the
# default RTD theme sidebar entries.
html_sidebars = {
    "**": [
        "versioning.html",
        "globaltoc.html",
        "relations.html",
        "sourcelink.html",
        "searchbox.html",
    ],
}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "oldp_doc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "oldp.tex",
        "Open Legal Data Platform Documentation",
        "Malte Schwarzer",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "oldp", "Open Legal Data Platform Documentation", [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "oldp",
        "Open Legal Data Platform Documentation",
        author,
        "OLDP",
        "One line description of project.",
        "Miscellaneous",
    ),
]
